pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = 'thenext/the-next-client'
        DOCKER_STORYBOOK_IMAGE_NAME = 'thenext/the-next-client-storybook'
        CONTAINER_NAME = 'the-next-client'
        STORYBOOK_CONTAINER_NAME = 'the-next-client-storybook'
        GITHUB_CREDENTIALS_ID = 'bonjin-github'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checkout Start'
                git branch: 'develop',
                    url: 'https://github.com/the-next-team/the-next-client',
                    credentialsId: GITHUB_CREDENTIALS_ID
            }
        }

        stage('Dockerizing') {
            parallel {
                stage('Build Client Image') {
                    steps {
                        sh "echo Image Build Start"
                        sh "docker build --target app . -t ${DOCKER_IMAGE_NAME}"
                    }
                    post {
                        success {
                            sh 'echo "Build Docker Image Success"'
                        }

                        failure {
                            sh 'echo "Build Docker Image Fail"'
                        }
                    }
                }
                stage('Build Storybook Image') {
                    steps {
                        sh "echo Storybook Image Build Start"
                        sh "docker build --target storybook . -t ${DOCKER_STORYBOOK_IMAGE_NAME}"
                    }
                    post {
                        success {
                            sh 'echo "Build Storybook Docker Image Success"'
                        }

                        failure {
                            sh 'echo "Build Storybook Docker Image Fail"'
                        }
                    }
                }
            }
        }

        stage('Deploy') {
            parallel {
                stage('Deploy Client') {
                    steps {
                        echo 'Deploy Start'
                        sh "docker stop ${CONTAINER_NAME} || true && docker rm ${CONTAINER_NAME} || true"
                        sh "docker run -d --name ${CONTAINER_NAME} -p 3080:80 ${DOCKER_IMAGE_NAME}"
                    }
                }
                stage('Deploy Storybook') {
                    steps {
                        echo 'Deploy Storybook Start'
                        sh "docker stop ${STORYBOOK_CONTAINER_NAME} || true && docker rm ${STORYBOOK_CONTAINER_NAME} || true"
                        sh "docker run -d --name ${STORYBOOK_CONTAINER_NAME} -p 6006:6006 ${DOCKER_STORYBOOK_IMAGE_NAME}"
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
        success {
            echo 'Pipeline succeeded.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
