name: Deploy

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Install Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

       - uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install and build
        run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Set PUBLIC_URL
        run: |
          PUBLIC_URL=$(echo $GITHUB_REPOSITORY | sed -r 's/^.+\/(.+)$/\/\1\//')
          echo PUBLIC_URL=$PUBLIC_URL > .env

      - name: Build app
        run: |
          yarn react:build
          cp ./build/index.html ./build/404.html

      # 이 부분입니다.
      # -----------------------------------------
      - name: Build storybook
        run: |
          yarn build-storybook
          mv ./storybook-static ./build/storybook
      # -----------------------------------------

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build